---
title: "Alternative delay plot"
author: "Group 4"
date: "`r Sys.Date()`"
output: pdf_document
# the following puts the knitted file in the Outputs folder
knit: (function(inputFile, encoding) {
      out_dir <- "../Outputs";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(colorspace)
```

```{r}
# Code to get the data for the basic IAH plot
## copied from delay-plot-starter-code.R
delays <- read_csv("http://vis.cwick.co.nz/data/all-summary.csv")
# see: 04-get-delay-summary.R for details of summarization

delays$DayOfWeek <- factor(delays$DayOfWeek, 
  levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))

# our plot for IAH
# iah <- subset(delays, Origin == "IAH")
# ggplot(iah, aes(DepHour, DayOfWeek)) +
#   geom_tile(aes(fill = prop_over_15)) 
# 
# # but now there are also flights from HOU 
# hou <- subset(delays, Origin == "HOU") %>% 
#   filter(Origin == "HOU")
```




```{r}

p=ggplot(delays, aes(x = DepHour, y = avg_delay/60, color = Origin)) +
  geom_line(stat = "summary", fun = mean, linewidth = 0.9) +
  labs(title = "To avoid delay, fly during the day!", 
       y = "Average Delay (hours)",
       caption = "Based on all departing flights from George Bush Intercontinental Airport (IAH) \nand William P. Hobby Airport (HOU) in 2011") +
  theme_classic() +
  scale_x_continuous("Departure time", 
    breaks = c(0, 6, 12, 18, 24),
    labels = c("Midnight", "6am", "Noon", "6pm", "Midnight"),
    expand = c(0, 0),
    limits = c(0, 23)) +
  scale_color_manual(label = c("George Bush \nIntercontinental Airport (IAH)", "William P. Hobby Airport (HOU)"), values = c("#440154FF", "#22A884FF"))+
  theme(legend.title = element_blank(),
        legend.position = "inside",
        plot.caption = element_text(hjust = 0))

# PNG version
ggsave("flight_delays.png", plot = p, width = 8, height = 5, units = "in", dpi = 300, path = "../Outputs")

# PDF version
ggsave("flight_delays.pdf", plot = p, width = 8, height = 5, units = "in", dpi = 300, path = "../Outputs")
```





